config/routes.rb
Rails.application.routes.draw do
  resources :images
  
  root 'comments#index'
  # get 'users/new', to: 'users#new'

  get 'comments/new', to: 'comments#new' #to create new messages and will use the same controller to handle them
  get 'comments', to: 'comments#index'
  post 'comments', to: 'comments#create' 
  get 'about', to: 'pages#about'
  resources :users, :only => [:new, :create, :destroy, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment, presence: true, length: {minimum: 10, maximum: 100}

end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  validates :user_name, presence: true, length: {minimum: 5, maximum: 10}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 105},
                    uniqueness: {case_sensitive: false},
                    format: {with: VALID_EMAIL_REGEX}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def create 
    @comment = Comment.new(comments_params)
    if @comment.save
      flash.alert = 'comment added'
      redirect_to comments_new_path
    else
      render 'new'
    end
  end


  private

  def comments_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[ show edit update destroy ]

  # GET /images or /images.json
  def index
    @images = Image.all
  end

  # GET /images/1 or /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: "Image was successfully created." }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:title, :author, :description, :public)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash.alert ="Account Created"
      redirect_to comments_new_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/comments/index.html.erb
<!--<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <title>Comentarios</title>
  </head>
  <body id="bg-colour">
     <div id="title">
      <h2>Que Gonorrea, Sin Pelos En la lengua</h2>
    </div> 
    <div class="flag-wrapper">
      <img src="images/bandera.png" alt="">

      image_tag("bandera.png") //ruby helper to display images on views
      <div class="text-wrapper">
        <h1>Que Gonorrea, sin pelos en la lengua</h1>
      </div>
    </div>
    <div>

     <p>que gonorrea esta vieja, se comio el ve</p>
    </div>
    
  </body>
</html> -->

  <div>
    <p>que gonorrea esta vieja, se comio el vecino</p>
  </div>

app/views/comments/new.html.erb
new  comment view
<%if @comment.errors.any?%>
  <ul>
    <%@comment.errors.full_messages.each do |error_comment|%>
      <li><%=error_comment%></li>
    <%end%>
  </ul>
<%end%>



<%= form_for @comment do |f| %>
  Write a comment: <%= f.text_field :comment %><br />
  <%= f.submit('Write comment') %>
<% end %>

app/views/images/_form.html.erb
<%= form_with(model: image) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :public %>
    <%= form.check_box :public %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Description</th>
      <th>Public</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.title %></td>
        <td><%= image.author %></td>
        <td><%= image.description %></td>
        <td><%= image.public %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @image.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @image.author %>
</p>

<p>
  <strong>Description:</strong>
  <%= @image.description %>
</p>

<p>
  <strong>Public:</strong>
  <%= @image.public %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QueGono</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h2>Que Gonorrea, Sin Pelos En la lengua</h2>
    <%= link_to "ver lo que estan diciendo", root_path %>
    <%= link_to "sobre que gonorrea", about_path %>
    <%= link_to "nuevo comentario", comments_new_path %>
    
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>sobre que gonorrea</h1>

app/views/users/new.html.erb
<br>sign up to comment
<br>

<%if @user.errors.any?%>
  <ul>
    <%@user.errors.full_messages.each do |error_message|%>
      <li><%=error_message%></li>
    <%end%>
  </ul>
<%end%>
<%= form_for @user do |f| %>
  Enter a user name: <%= f.text_field :user_name %><br />
  Enter your email : <%= f.email_field :email %><br />
  <%= f.submit('Create account to comment') %>
<% end %>